############################################################
# Rest Client API実行ファイル
############################################################

#----------------------------------------------------
# endpoint :
#----------------------------------------------------
### @name METHODNAME_endpoint


###
